version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: crm_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rpass
      MYSQL_DATABASE: u1957399_mini_crm
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crm_password
    volumes:
      - ./u1957399_mini_crm.sql:/docker-entrypoint-initdb.d/u1957399_mini_crm.sql
      - db_data:/var/lib/mysql

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    # depends_on:
    #   - backend
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  db_data:
